# Generated by Django 3.2.15 on 2023-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=25, null=True, verbose_name='first name')),
                ('second_name', models.CharField(default=None, max_length=25, null=True, verbose_name='second name')),
                ('last_name', models.CharField(default=None, max_length=25, null=True, verbose_name='last name')),
                ('phone', models.CharField(default=None, max_length=15, null=True, verbose_name='number phone')),
                ('birthday', models.DateField(default=None, null=True, verbose_name='birthday')),
                ('classroom', models.CharField(default=None, max_length=12, null=True, verbose_name='classroom')),
                ('is_child', models.BooleanField(default=False, verbose_name='is this a child?')),
                ('phone_parents', models.CharField(default=None, max_length=18, null=True, verbose_name='number phone parents')),
                ('photo', models.ImageField(default=None, null=True, upload_to='student', verbose_name='photo student')),
            ],
        ),
    ]
