# Generated by Django 3.2.15 on 2023-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(default=None, max_length=12, null=True, verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='number phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_parents',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='number phone parents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='student', verbose_name='photo student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='second name'),
        ),
    ]
