# Generated by Django 3.2.15 on 2023-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20231002_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_parents',
            field=models.CharField(default=None, max_length=18, null=True, verbose_name='number phone parents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='second name'),
        ),
    ]
