# Generated by Django 3.2.15 on 2023-10-24 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_file', models.FileField(blank=True, upload_to='homework', verbose_name='Домашнее задание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('homework_text', models.TextField(blank=True, verbose_name='Домашнее задание')),
            ],
        ),
        migrations.CreateModel(
            name='NotStandardDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('is_work', models.BooleanField(default=False, verbose_name='Это рабочий день?')),
            ],
            options={
                'verbose_name': 'Нестандартный рабочий день',
            },
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала занятий')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальное время?')),
            ],
            options={
                'verbose_name': 'Время начала занятий',
                'verbose_name_plural': 'Время начала занятий',
            },
        ),
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Ученик')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex=re.compile('(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d'))], verbose_name='Номер телефона')),
                ('classroom', models.IntegerField(verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Пробное занятие',
                'verbose_name_plural': 'Пробные занятия',
            },
        ),
        migrations.CreateModel(
            name='TypeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Тип занятия')),
                ('is_group_lesson', models.BooleanField(default=False, verbose_name='Групповое занятие')),
                ('available_trial_lesson', models.BooleanField(default=False, verbose_name='Доступно для пробной записи?')),
                ('duration', models.IntegerField(default=60, verbose_name='Продолжительность занятия (минуты)')),
                ('cost', models.IntegerField(default=1000, verbose_name='Стоимость (рубли)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Занятие')),
            ],
        ),
    ]
