# Generated by Django 3.2.15 on 2023-10-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='type lessons')),
                ('is_group_lesson', models.BooleanField(default=False, verbose_name='is this a group lesson?')),
                ('duration', models.IntegerField(default=60, verbose_name='duration lesson (minutes)')),
                ('cost', models.IntegerField(default=1000, verbose_name='cost lesson (ruble)')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson')),
            ],
        ),
    ]
