# Generated by Django 3.2.15 on 2023-10-08 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20231006_1540'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex=re.compile('(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d'))], verbose_name='Номер телефона')),
                ('classroom', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='typelesson',
            name='available_trial_lesson',
            field=models.BooleanField(default=False, verbose_name='Доступно для пробной записи?'),
        ),
        migrations.AddField(
            model_name='typelesson',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typelesson',
            name='cost',
            field=models.IntegerField(default=1000, verbose_name='Стоимость (рубли)'),
        ),
        migrations.AlterField(
            model_name='typelesson',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Продолжительность занятия (минуты)'),
        ),
        migrations.AlterField(
            model_name='typelesson',
            name='is_group_lesson',
            field=models.BooleanField(default=False, verbose_name='Групповое занятие'),
        ),
        migrations.AlterField(
            model_name='typelesson',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Тип занятия'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='triallesson',
            name='type_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson'),
        ),
    ]
