# Generated by Django 3.2.15 on 2023-10-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('main', '0002_visitors_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='triallesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.starttime', verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='type_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson', verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.starttime', verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson', verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='homeworkfile',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Занятие'),
        ),
    ]
