# Generated by Django 3.2.15 on 2023-10-12 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20231006_1540'),
        ('teachers', '0003_auto_20231006_1540'),
        ('main', '0002_auto_20231008_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('homework_text', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='NotStandardDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('is_work', models.BooleanField(default=False, verbose_name='Это рабочий день?')),
            ],
            options={
                'verbose_name': 'Нестандартный рабочий день',
            },
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала занятий')),
                ('actual', models.BooleanField(default=True, verbose_name='Актуальное время?')),
            ],
            options={
                'verbose_name': 'Время начала занятий',
                'verbose_name_plural': 'Время начала занятий',
            },
        ),
        migrations.AlterModelOptions(
            name='triallesson',
            options={'verbose_name': 'Пробное занятие', 'verbose_name_plural': 'Пробные занятия'},
        ),
        migrations.AlterModelOptions(
            name='typelesson',
            options={'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Типы занятий'},
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='classroom',
            field=models.IntegerField(verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='type_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson', verbose_name='Тип занятия'),
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.starttime', verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson', verbose_name='Тип занятия'),
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_file', models.FileField(blank=True, upload_to='homework', verbose_name='Домашнее задание')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson', verbose_name='Занятие')),
            ],
        ),
        migrations.AlterField(
            model_name='triallesson',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.starttime', verbose_name='Время'),
        ),
    ]
