# Generated by Django 3.2.15 on 2023-10-24 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_visitors_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=25, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(default=None, max_length=25, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex=re.compile('(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d'))], verbose_name='Номер телефона')),
                ('birthday', models.DateField(default=None, null=True, verbose_name='День рождения')),
                ('photo', models.ImageField(default=None, null=True, upload_to='teacher', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('type_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson')),
            ],
        ),
    ]
