# Generated by Django 3.2.15 on 2023-10-04 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='student', verbose_name='photo student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='number phone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
