# Generated by Django 3.2.15 on 2023-10-06 12:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20231004_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex=re.compile('(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d'))], verbose_name='number phone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='teacher', verbose_name='photo teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='second name'),
        ),
    ]
