# Generated by Django 3.2.15 on 2023-10-12 03:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20231012_0619'),
        ('teachers', '0003_auto_20231006_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный номер телефона', regex=re.compile('(?:\\+|\\d)[\\d\\-\\(\\) ]{9,}\\d'))], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='teacher', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('type_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typelesson')),
            ],
        ),
    ]
